api:
  container_name: "sxapi-demo-openshift-api"
  build: api/
  environment:
  - SX_VERBOSE=true
  - SX_DEBUG=true
  ports:
    - "8080:8080"
  volumes:
  - "/secure/dev/startx/sxapi-demo-openshift/api:/app:Z"
  command: ["/bin/sx-nodejs" , "run"]

www:
  container_name: "sxapi-demo-openshift-www"
  build: www/
  environment:
  - SX_VERBOSE=true
  - SX_DEBUG=true
  - DEMO_API=api-test.openshift.demo.startx.fr
  ports:
    - "8081:8080"
  volumes:
  - "/secure/dev/startx/sxapi-demo-openshift/www:/app:Z"
  command: ["/bin/sx-nodejs" , "run"]

db:
  container_name: "sxapi-demo-openshift-db"
  image: startx/sv-mariadb:latest
  environment:
  - SX_VERBOSE=true
  - SX_DEBUG=true
  ports:
    - "3306:3306"
  volumes:
  - "./db:/tmp/sql:z"
  command: ["/bin/sx-mariadb" , "build" ]
#  command: ["/bin/sx-mariadb" , "run" ]