#!/bin/bash
if [ "$1" == "" ]; then
   echo "please give the DNS name coresponding to this cluster (ex: openshift.demo.startx.fr)";
   exit 1;
fi
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root"
   exit 1;
fi
echo "== Start openshift origin"
oc cluster up --logging --metrics --service-catalog  --public-hostname=$1 --routing-suffix=$1
echo "== Authenticate as administrator in openshift origin"
oc login -u system:admin