#!/bin/bash
if [ "$DNSNAME" == "" ]; then
   echo "please set your domainname using the environent variable DNSNAME (ex: export DNSNAME=my.example.com";
   exit 1;
fi
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root"
   exit 1;
fi
grep -i "release 7" /etc/redhat-release
if [ $? != 0 ]; then
   echo "This script must be run in a Centos 7 release"
   exit 1;
fi
grep -i "CentOS Linux" /etc/redhat-release
if [ $? != 0 ]; then
   echo "This script must be run in a Centos 7 OS"
   exit 1;
fi

export RELEASE=3.9.0
export PACKAGE=v$RELEASE-191fece
export INSTALL=/openshift-origin-3.9.0

echo "== Update system"
yum update -y

echo "== Install dependencies"
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
yum install -y --enablerepo=epel wget git net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct atomic docker-1.13.1  ansible pyOpenSSL

echo "== Enable insecure registry"
echo "{\"insecure-registries\" : [ \"172.30.0.0/16\" ]}" > /etc/docker/daemon.json

echo "== Start docker daemon"
systemctl daemon-reload
systemctl restart docker

echo "== Download openshift origin $RELEASE"
wget https://github.com/openshift/origin/releases/download/v$RELEASE/openshift-origin-server-$PACKAGE-linux-64bit.tar.gz
tar xzvf openshift-origin-server-$PACKAGE-linux-64bit.tar.gz
mv openshift-origin-server-$PACKAGE-linux-64bit $INSTALL
rm -f openshift-origin-server-$PACKAGE-linux-64bit.tar.gz
cd $INSTALL

echo "== Install openshift origin $RELEASE"
export PATH=/openshift-origin-$RELEASE:$PATH
export KUBECONFIG=$INSTALL/openshift.local.config/master/admin.kubeconfig
export CURL_CA_BUNDLE=$INSTALL/openshift.local.config/master/ca.crt
sudo chmod +r $INSTALL/openshift.local.config/master/admin.kubeconfig

echo 'export PATH=/openshift-origin-$RELEASE:$PATH' >> ~/.bashrc
.  ~/.bashrc
echo "== End installation of openshift origin $RELEASE"